// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskNeo(arg1) {
  return window['go']['main']['App']['AskNeo'](arg1);
}

export function CheckSingleInstance() {
  return window['go']['main']['App']['CheckSingleInstance']();
}

export function GetAutoStartStatus() {
  return window['go']['main']['App']['GetAutoStartStatus']();
}

export function GetCurrentHotkey() {
  return window['go']['main']['App']['GetCurrentHotkey']();
}

export function GetGeminiAPIKey() {
  return window['go']['main']['App']['GetGeminiAPIKey']();
}

export function GetWhatsAppStatus() {
  return window['go']['main']['App']['GetWhatsAppStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetGeminiAPIKey(arg1) {
  return window['go']['main']['App']['SetGeminiAPIKey'](arg1);
}

export function SetHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetHotkey'](arg1, arg2);
}

export function ShowChat() {
  return window['go']['main']['App']['ShowChat']();
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleAutoStart(arg1) {
  return window['go']['main']['App']['ToggleAutoStart'](arg1);
}
