// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AskNeo(arg1:string):Promise<string>;

export function CheckSingleInstance():Promise<void>;

export function GetAutoStartStatus():Promise<boolean>;

export function GetCurrentHotkey():Promise<string>;

export function GetGeminiAPIKey():Promise<string>;

export function GetWhatsAppStatus():Promise<main.WhatsAppStatusResponse>;

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;

export function SetGeminiAPIKey(arg1:string):Promise<boolean>;

export function SetHotkey(arg1:string,arg2:string):Promise<boolean>;

export function ShowChat():Promise<void>;

export function ShowSettings():Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleAutoStart(arg1:boolean):Promise<string>;

export function TranscribeAudio(arg1:string,arg2:string):Promise<string>;
